# This file is used to build the baackend application. Aplication is Strapi CMS.

name: 01 - Build Backend Application

on:
  workflow_dispatch:
  workflow_call:

jobs:
    build:
        permissions:
          contents: read
          issues: read
          checks: write
          pull-requests: write
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - name: Set up Node.js 18.20.4
          uses: actions/setup-node@v4
          with:
            node-version: 18.20.5
            cache: 'npm'
            cache-dependency-path: backend/package-lock.json
    
        - name: Install backend dependencies
          working-directory: backend
          run: npm ci
    
        - name: Build backend application
          working-directory: backend
          run: npm run build
