name: 06 - k6 Load Test

on:
    workflow_dispatch:
    workflow_call:

jobs:
  run-test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # Configurar k6
      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      # EJECUCIÓN LOCAL DE PRUEBAS DE CARGA
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: frontend/src/k6/tests_load_k6.js

      # EJECUCIÓN DE PRUEBAS DE CARGA CON GRAFANA
#      - name: Run nube k6 test
#        uses: grafana/run-k6-action@v1
#        env:
#          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }} # Token para usar k6 Cloud (opcional)
#          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
#        with:
#          path: frontend/src/k6/tests_load_k6.js