name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  # 02 - Frontend - Unit test
  unit_test_frontend:
    name: unit_test_frontend
    uses: ./.github/workflows/unit_test_frontend.yml
    secrets: inherit

  

  

