name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  

  # 04 - SAST - Static Application Security Testing
  sast:
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit
    
  

  

