name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Construction
    runs-on: ubuntu-latest
    steps:
      - run: echo "Group: Construction"
  
  build_frontend:
    needs: build
    name: Build Frontend Application
    uses: ./.github/workflows/build_frontend.yml
    secrets: inherit

  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - run: echo "Group: Analysis"

  sast:
    needs: analysis
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  slint:
    needs: analysis
    name: Lint React Code
    uses: ./.github/workflows/slint.yml
    secrets: inherit

  license_compliance:
    needs: analysis
    name: License Compliance
    uses: ./.github/workflows/license_compliance.yml
    secrets: inherit

  

