name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:

  # 02 - Build Frontend Application
  build_frontend:
    name: Build Frontend Application
    uses: ./.github/workflows/build_frontend.yml
    secrets: inherit

  # 03 - Build Backend Application
  build_backend:
    name: Build Backend Application
    uses: ./.github/workflows/build_backend.yml
    secrets: inherit

  # 05 - SAST - Static Application Security Testing
  #sast:
    #needs: build_frontend
    #name: SAST
    #uses: ./.github/workflows/sast.yml
    #secrets: inherit
    
  # 06 - SCA - Software Composition Analysis
  #sca:
    #needs: build_frontend
    #name: SCA
    #uses: ./.github/workflows/sca.yml
    #secrets: inherit
    
  # 07 - k6 Load Test
  #k6:
   # needs: build_frontend
    #name: k6 Load Test
    #uses: ./.github/workflows/k6.yml
    #secrets: inherit

  # 08 - Lint React Code
  slint:
    needs: build_frontend
    name: Lint React Code
    uses: ./.github/workflows/slint.yml
    secrets: inherit

  # 09 - License Compliance
  #license_compliance:
    #needs: [build_frontend, build_backend]
    #name: License Compliance
    #uses: ./.github/workflows/license_compliance.yml
    #secrets: inherit
