name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  # Frontend - Unit test
  unit_test_frontend:
    name: unit_test_frontend
    uses: ./.github/workflows/unit_test_frontend.yml
    secrets: inherit

  # Backend - Unit test
  unit_test_backend:
    name: unit_test_backend
    uses: ./.github/workflows/unit_test_backend.yml
    secrets: inherit
    
  # SCA - Security Code Analysis
  sca:
    #needs: build_frontend
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit
  
  # k6 - Load test
  k6:
    name: k6
    uses: ./.github/workflows/k6.yml
    secrets: inherit

  # SAST - Static Application Security Testing
  sast:
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit