name: Lint and Format Check

# Ejecutar en cada push y pull request
on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      # Extrae el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # o la versión que uses en tu proyecto

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar ESLint para verificar sintaxis
      - name: Run ESLint
        run: npm run lint

      # Verificar el formato del código con Prettier
      - name: Run Prettier
        run: npm run format
