name: React Unit Tests 
on: [push, pull_request] 
jobs: 
  test: 
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./frontend  # Ajusta esta ruta al directorio de tu proyecto
    steps: 
    - uses: actions/checkout@v3 
    - name: Use Node.js 
      uses: actions/setup-node@v3 
      with: 
        node-version: '18.20.4' 
    - name: Install dependencies 
      run: npm install
    - name: Run tests 
      run: npm test -- --watchAll=false
